name: Lint Go code

on:
  pull_request:
    branches:
      - "main"
      - "release-*"
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "sec-scanners-config.yaml"
      - CODEOWNERS
      - LICENSE
      - LICENSES
      - OWNERS
      - OWNERS_ALIASES
      - PROJECT


jobs:
  code-linter:
    name: "Run golangci-lint"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21 # This can be a specific version. E.g. 1.19 or 1.21.x

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Super-linter
        uses: super-linter/super-linter@v6.3.0  # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
