name: Lint PR Title
run-name: ${{github.event.pull_request.title}}

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  check:
    name: Check Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@7ed886f1bd917d19cb9d6ce6c10e80e81fa31c39
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            deps
            chore
            docs
            feat
            fix
            refactor
            test
          requireScope: false
          # https://regex101.com/r/pmEvPq/2
          subjectPattern: ^(?![A-Z]).+$
