name: golangci-lint

on:
  pull_request:
    branches:
      - main
      - "release-**"
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "sec-scanners-config.yaml"
      - CODEOWNERS
      - LICENSE
      - LICENSES
      - OWNERS
      - OWNERS_ALIASES
      - PROJECT

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  unit-test:
    name: "Run golangci-lint"
    uses: kyma-project/eventing-tools/.github/workflows/lint-go-reusable.yml@main
