name: Lint Go code

on:
  pull_request:
    branches:
      - "main"
      - "release-*"
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "sec-scanners-config.yaml"
      - CODEOWNERS
      - LICENSE
      - LICENSES
      - OWNERS
      - OWNERS_ALIASES
      - PROJECT

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
  # Optional: Allow write access to checks to allow the action to annotate code in the PR.
  checks: write

jobs:
  code-linter:
    name: "Run golangci-lint"
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21 # This can be a specific version. E.g. 1.19 or 1.21.x

      - name: Checkout code
        uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
